### ISSUE TITLE
AD endpoint URI

### ISSUE THREAD

**Issue by ktk** [clncln1/node-asclient#1]
First, thanks a lot for the code, I'm looking for something like this for a long time!

I try to figure out how to connect to an AD server. I don't know much about AD and so far all I had to provide was `myuser@mydomain.com` and systems like MacOS know how to connect to it. I have a Exchange web interface at `https://myexchange.mydomain.com` so I created `https://myexchange.mydomain.com/Microsoft-Server-ActiveSync` but that didn't seem to work. A CURL on that URI returns a `401` with `Unauthorized` so at least it seems to resolve something.

If I connect with the sample code all I see is `Error: The server didnt respond properly`.

Can you give some more hints about what I could try to get the sample working?

**Comment by clncln1** [comment]
It is assumed that the Exchange server supports NTLM authentication.
Not sure how your server is configured. Could you do a curl again and let me know the value of the `www-authenticate` header

**Comment by ktk** [comment]
Thanks for the feedback, I get:

```
WWW-Authenticate: Basic realm="myexchange.mydomain.com"
```

**Comment by ktk** [comment]
Checked some postings at Stackoverflow, see https://stackoverflow.com/questions/4265975/authentication-issues-with-www-authenticate-negotiate. It seems that this server really simply assumes basic auth from what I can see. Would you agree with this?

If so I could try to hack basic auth into it instead of NTLM auth.

**Comment by ktk** [comment]
I tried doing basic auth via curl, does not work out with my domain user. So not sure if this is gonna work that way. What I didn't mention yet is that this is a stone old Exchange server, IIRC 2003. So might well be the problem as well.

**Comment by clncln1** [comment]
Yeah, I could definitely add a fallback to Basic Auth, but if you don't get it to work via curl, I am afraid it seems to be a server config issue then.

**Comment by clncln1** [comment]
Added Basic auth fallback in clncln1/node-ntlm-client@654860a
Version bumped to 0.1.0 due to behavior change.

This is an alternative - imho cleaner - change to #2
